name: Build MikaKernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "ANYKERNEL_SOURCE=$(grep -w "ANYKERNEL_SOURCE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE_BRANCH=$(grep -w "ANYKERNEL_SOURCE_BRANCH" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE=$(grep -w "KERNEL_SOURCE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE_BRANCH=$(grep -w "KERNEL_SOURCE_BRANCH" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_CONFIG=$(grep -w "KERNEL_CONFIG" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV

      - name: Pull Toolchains
        run: |
          # Pull Proton Clang
          mkdir clang
          curl -L https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.tar.gz -o clang.tar.gz
          tar -C clang/ --strip-components=1 -xf clang.tar.gz
          
          # Pull GCC 64-bit
          mkdir gcc64
          curl -L https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/archive/refs/heads/lineage-19.1.tar.gz -o gcc64.tar.gz
          tar -C gcc64/ --strip-components=1 -xf gcc64.tar.gz

          # Pull GCC 32-bit
          mkdir gcc32
          curl -L https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9/archive/refs/heads/lineage-19.1.tar.gz -o gcc32.tar.gz
          tar -C gcc32/ --strip-components=1 -xf gcc32.tar.gz

      - name: Pull Kernel Source
        run: |
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source

      - name: Build Kernel
        run: |
          export PATH=$GITHUB_WORKSPACE/clang/bin:$GITHUB_WORKSPACE/gcc64/bin:$GITHUB_WORKSPACE/gcc32/bin:${PATH}
          export KBUILD_BUILD_USER="zclkkk"
          export KBUILD_BUILD_HOST="workspace"
          
          # Toolchain prefixes for Proton Clang + Lineage GCC
          export CLANG_PARAMS="CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- LLVM=1 LLVM_IAS=1"
          
          cd kernel-source
          
          # 1. Generate base config
          make ARCH=arm64 $CLANG_PARAMS ${{ env.KERNEL_CONFIG }}
          
          # 2. Fix the PRIME_CPU_MASK bug and enable UAC2 Audio
          ./scripts/config --file .config --set-val PRIME_CPU_MASK 0
          ./scripts/config --file .config --enable USB_CONFIGFS_F_UAC2
          ./scripts/config --file .config --enable USB_CONFIGFS_F_UAC1
          ./scripts/config --file .config --enable USB_G_AUDIO
          
          # 3. Non-interactive config sync
          make ARCH=arm64 $CLANG_PARAMS olddefconfig
          
          # 4. Compilation
          make -j$(nproc --all) ARCH=arm64 $CLANG_PARAMS
